LoginApp1/Models/Account/AppRole.cs
using Microsoft.AspNet.Identity.EntityFramework;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace LoginApp1.Models.Account
{
    [Table("AspNetRoles")]
    [FluentValidation.Attributes.Validator(typeof(AppRoleValid))]
    public class AppRole : IdentityRole
    {
        public AppRole() : base()
        {  }
        public AppRole(string name) : base(name)
        {  }

        [Display(Name = "Role Id")]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        [Index("IX_RoleId", IsUnique = true)]
        public int RoleId{ get; set; }

        [Display(Name = "Role Description")]
        [StringLength(50)]
        public string Description { get; set; }

        [Display(Name = "Create Date")]
        public DateTime CreateDate { get; set; }

        [Display(Name = "User Count")]
        [NotMapped]
        public int UserCount { get; set; }

    }
}

LoginApp1/Models/Account/AppRoleView.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace LoginApp1.Models.Account
{
    public class AppRoleView
    {
        public string key { get; set; }
        public string message { get; set; }
        public string status { get; set; }

        public AppRole appRole { get; set; }
        public List<AppRole> appRoles { get; set; }
        public List<AppUser> appUsers { get; set; }
        public List<AppUser> srchUsers { get; set; }

        [Display(Name = "Email")]
        [StringLength(50)]
        public string Email { get; set; }

        [Display(Name = "First Name")]
        [StringLength(50)]
        public string FirstName { get; set; }

        [Display(Name = "Last Name")]
        [StringLength(50)]
        public string LastName { get; set; }

    }
}

LoginApp1/Models/Account/SearchUsers.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace LoginApp1.Models.Account
{
    public class SearchUsers
    {

        [Display(Name = "Email")]
        [StringLength(50)]
        [NotMapped]
        public string Email { get; set; }

        [Display(Name = "First Name")]
        [StringLength(50)]
        [NotMapped]
        public string FirstName { get; set; }

        [Display(Name = "Last Name")]
        [StringLength(50)]
        [NotMapped]
        public string LastName { get; set; }

    }
}

LoginApp1/Controllers/AppRolesController.cs
using LoginApp1.Classes;
using LoginApp1.Classes.Account;
using LoginApp1.DataConnections;
using LoginApp1.Models.Account;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.Owin;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace LoginApp1.Controllers
{
    public class AppRolesController : Controller
    {

        // ===============================================================================
        public ActionResult IndexAppRoles()
        {
            using (var roleManager1 = HttpContext.GetOwinContext().Get<AppRoleManager>())
            {
                var t_roles = roleManager1.Roles.ToList();
                AppRoleView model = new AppRoleView();
                model.appRoles = roleManager1.Roles.ToList();
                model.status = "Init";
                return View(model);
            }
        }

        // ===============================================================================
        public ActionResult DeleteAppRole(AppRoleView model)
        {
            using (var role_Manager = HttpContext.GetOwinContext().Get<AppRoleManager>())
            {
                AppRole appRole = role_Manager.FindById(model.key);
                if (appRole != null)
                {
                    role_Manager.Delete(appRole);
                    model.status = "OK";
                    model.message = "Role was deleted.";
                }
                else
                {
                    model.status = "Error";
                    model.message = "Role was not found.";
                }
                model.appRoles = role_Manager.Roles.ToList();
                return PartialView("IndexAppRolesPartial", model);
            }
        }

        // ===============================================================================
        [HttpGet]
        public ActionResult EditAppRole(string id)
        {
            AppRoleView model = new AppRoleView();
            using (var role_Manager = HttpContext.GetOwinContext().Get<AppRoleManager>())
            {
                AppRole appRole = role_Manager.Roles.FirstOrDefault(f => f.Id == id);
                if (appRole != null)
                {
                    model.appRole = appRole;
                    model.appUsers = GetUsersByRole(appRole);
                }
                // !!! else - handle not found, when id not null !!!
            }
            return View(model);
        }

        // ===============================================================================
        [HttpPost]
        public ActionResult EditAppRole(AppRoleView model, string save, string search)
        {
            System.Threading.Thread.Sleep(200);
            dynamic jsonMessage;

            if (!ModelState.IsValid)
            {
                Dictionary<string, string> modelErrors = GetModelErrors.GetErrors(ModelState);
            }
            else
            {
                using (var role_Manager = HttpContext.GetOwinContext().Get<AppRoleManager>())
                {
                    AppRole appRole = role_Manager.Roles.FirstOrDefault(f => f.Id == model.appRole.Id);
                    if (appRole == null)
                    {
                        appRole = new AppRole();
                        appRole.Name = model.appRole.Name;
                        appRole.Description = model.appRole.Description;
                        appRole.CreateDate = DateTime.Now;
                        role_Manager.Create(appRole);
                        jsonMessage = new { param1 = "RoleName", param2 = "", param3 = "Role was created." };
                        HttpContext.Response.StatusCode = (int)HttpStatusCode.OK;
                        return Json(jsonMessage, JsonRequestBehavior.AllowGet);
                    }

                    appRole.Description = model.appRole.Description;
                    role_Manager.Update(appRole);
                    jsonMessage = new { param1 = "RoleName", param2 = "OK", param3 = "Role was updated." };
                    HttpContext.Response.StatusCode = (int)HttpStatusCode.OK;
                    return Json(jsonMessage, JsonRequestBehavior.AllowGet);
                }
            }
            return View(model);
        }



        // ===============================================================================
        [HttpGet]
        public ActionResult AddUserRole()
        {
            int roleId = 35; 

            AppRoleView model = new AppRoleView();
            model.status = "Init";

            using (var roleManager1 = HttpContext.GetOwinContext().Get<AppRoleManager>())
            { model.appRole = roleManager1.Roles.Where(w => w.RoleId == roleId).ToList().FirstOrDefault(); }

            using (var userManager = HttpContext.GetOwinContext().Get<AppUserManager>())
            {
                model.appUsers = GetUsersByRole(model.appRole); //userManager.Users.ToList();
                model.srchUsers = userManager.Users.ToList();

                foreach (AppUser srchUser in model.srchUsers.ToList())
                {
                    AppUser testUser = model.appUsers.Where(w => w.Id == srchUser.Id).FirstOrDefault();
                    if (testUser != null)
                    {
                        model.srchUsers.Remove(srchUser);
                    }
                }

            }

            return View(model);
        }

        // ===============================================================================
        [HttpPost]
        public ActionResult AddUserRole(AppRoleView model)
        {
            System.Threading.Thread.Sleep(500);
            dynamic jsonMessage;

            if (!ModelState.IsValid)
            {
                Dictionary<string, string> modelErrors = GetModelErrors.GetErrors(ModelState);
                jsonMessage = new { param1 = "ModelState", param2 ="Error", param3 = modelErrors.ToList()[0].Value };
                HttpContext.Response.StatusCode = (int)HttpStatusCode.NotModified;
                return Json(jsonMessage, JsonRequestBehavior.AllowGet);
            }
            else
            {

                if (model.status == "AddUser")
                {
                    using (var userManager = HttpContext.GetOwinContext().Get<AppUserManager>())
                    {
                        userManager.AddToRole(model.key, model.appRole.Name);
                        jsonMessage = new { param1 = "AddUserRole", param2 = model.key, param3 = "User was added to role." };
                        HttpContext.Response.StatusCode = (int)HttpStatusCode.OK;
                        return Json(jsonMessage, JsonRequestBehavior.AllowGet);
                    }
                }
                if (model.status == "RemoveUser")
                {
                    using (var userManager = HttpContext.GetOwinContext().Get<AppUserManager>())
                    {
                        userManager.RemoveFromRole(model.key, model.appRole.Name);
                        jsonMessage = new { param1 = "RemoveUserRole", param2 = model.key, param3 = "User was removed from role." };
                        HttpContext.Response.StatusCode = (int)HttpStatusCode.OK;
                        return Json(jsonMessage, JsonRequestBehavior.AllowGet);
                    }
                }

                if (model.status == "SearchUsers")
                {
                    List<AppUser> tmp_list = AppUserProcs.GetUsers(model);
                    model.srchUsers = tmp_list;
                    jsonMessage = new { param1 = "param1", param2 = "param2", param3 = "param2" };
                    string jsonString = Newtonsoft.Json.JsonConvert.SerializeObject(jsonMessage);
                    HttpContext.Response.AddHeader("srchMessage", jsonString);
                    HttpContext.Response.StatusCode = (int)HttpStatusCode.OK;
                    return PartialView("SrchUsersTable", model);
                }

            }
            return View(model);
        }

        //===============================================================================
        private static List<AppUser> GetUsersByRole(AppRole appRole)
        {
            List<AppUser> rtn_list = new List<AppUser>();
            using (var db_context = new SqlExpIdentity())
            {
                var users1 = appRole.Users.Select(s => s.UserId).ToList();
                rtn_list = db_context.Users.Where(w => users1.Contains(w.Id)).ToList();
            }
            return rtn_list;
        }

    }
}

LoginApp1/Views/AppRoles/AddUserRole.cshtml
@model LoginApp1.Models.Account.AppRoleView

@{
    ViewBag.Title = "AddUserRole";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@using (Ajax.BeginForm("AddUserRole", "AppRoles", null,
    new AjaxOptions
    {
        HttpMethod = "Post",
        OnBegin = "OnBegin",
        OnFailure = "OnFailure(xhr, status)",
        OnSuccess = "OnSuccess(data, status, xhr)"
    },
    new { id = "myform" }))
{

    @Html.AntiForgeryToken()
    @Html.HiddenFor(m => m.appRole.Id)
    @Html.HiddenFor(m => m.appRole.RoleId)
    @Html.HiddenFor(m => m.appRole.Name)
    @Html.HiddenFor(m => m.appRole.Description)
    @Html.HiddenFor(m => m.status, new { @id = "hdn_status" })
    @Html.HiddenFor(m => m.key, new { @id = "hdn_key" })

    <div class="logo mb-3">
        <div class="col-md-12 text-center">
            <h2>Add or remove users for this role</h2>
        </div>
    </div>

    <div class="col-xs-1"></div>
    <div class="col-xs-10">

        <div>
            @Html.ActionLink("Back to roles list", "IndexAppRoles")
        </div>
        <div class="form-horizontal">
            <hr class="margin_bottom_small" />
            <div class="row margin_bottom_small">
                <div class="col-xs-3 margin_bottom_small float_left">
                    @Html.LabelFor(model => model.appRole.RoleId, htmlAttributes: new { @class = "control-label  float_left" }):
                    @Html.EditorFor(model => model.appRole.RoleId, new { htmlAttributes = new { @id = "RoleId", @class = "form-control float_left", @disabled = "disabled" } })
                </div>
                <div class="col-xs-4 margin_bottom_small">
                    @Html.LabelFor(model => model.appRole.Name, htmlAttributes: new { @class = "control-label" }):
                    @Html.EditorFor(model => model.appRole.Name, new { htmlAttributes = new { @id = "RoleName", @class = "form-control", @disabled = "disabled" } })
                </div>
                <div class="col-xs-5">
                    @Html.LabelFor(model => model.appRole.Description, htmlAttributes: new { @class = "control-label" }):
                    @Html.EditorFor(model => model.appRole.Description, new { htmlAttributes = new { @id = "RoleDescription", @class = "form-control ", @disabled = "disabled" } })
                </div>
            </div>
            <hr class="margin_top_none margin_bottom_none" />
        </div>
    </div>
    <div class="col-xs-1"></div>
    <br style="clear:both;" />

    <div class="form-horizontal">
        <div class="col-xs-1"></div>
        <div class="col-xs-10">
            <h4>Search for users to add to this role:</h4>
            <div class="row margin_bottom_small">
                <div class="col-xs-2 margin_bottom_small">
                    @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label" })
                    @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @id = "SrchEmail", @class = "form-control small_inp_box" } })
                </div>
                <div class="col-xs-3  margin_left_1em">
                    @Html.LabelFor(model => model.FirstName, htmlAttributes: new { @class = "control-label" })
                    @Html.EditorFor(model => model.FirstName, new { htmlAttributes = new { @id = "SrchFirstName", @class = "form-control small_inp_box" } })
                </div>
                <div class="col-xs-4  margin_left_1em">
                    @Html.LabelFor(model => model.LastName, htmlAttributes: new { @class = "control-label" })
                    @Html.EditorFor(model => model.LastName, new { htmlAttributes = new { @id = "SrchLastName", @class = "form-control small_inp_box" } })
                </div>
                <div class="col-xs-1  margin_left_2em">
                    <label class="control-label">&nbsp;</label>
                    <label class="control-label">&nbsp;</label>
                    <input type="submit" 
                           id="btn_search" 
                           name="Search" 
                           value="Search" 
                           class="btn btn-default btn-primary" 
                           onclick="javascript: return SearchUsers();"/>
                </div>
            </div>
        </div>
        <div class="col-xs-1"> </div>
    </div>
    <br style="clear:both;" />


    <div class="form-horizontal">
        <div class="col-xs-1"></div>
        <div class="col-xs-10">
            <h5 class="bold float_left">Search results:</h5>
            <div id="div_add_message" class="lcl_hidden">@Html.Partial("~/Views/CommonPartial/Message1.cshtml")</div>
            <div id="div_usersearch">@Html.Partial("~/Views/AppRoles/SrchUsersTable.cshtml", Model)</div>
            <br style="clear:both;" />
            <hr class="margin_bottom_vsmall margin_top_vsmall" />
        </div>
        <div class="col-xs-1"></div>
        <br style="clear:both;" />
    </div>


    <div class="form-horizontal">
        <div class="col-xs-1"></div>
        <div class="col-xs-10">
            <h5 class="bold float_left ">Assigned users:</h5>
            <div id="div_remove_message" class="lcl_hidden">@Html.Partial("~/Views/CommonPartial/Message1.cshtml")</div>
            <div id="div_roleusers">@Html.Partial("~/Views/AppRoles/RoleUsersTable.cshtml", Model)</div>
            <br style="clear:both;" />
            <hr class="margin_bottom_vsmall margin_top_vsmall" />
        </div>
        <div class="col-xs-1"></div>
        <br style="clear:both;" />
    </div>
}


@section scripts{
    <script>
        // --------------------------------------------------------------------------------
        $(document).ready(function () {
            console.log("EditAppRole: ready to rock and roll....");
            $(".small_inp_box:first").focus();
            $(".small_inp_box").addClass("lgreen");

            $("#div_usersearch").find("#tbl_usersearch").dataTable({
                searching: false, info: false, lengthChange: false 
            });


            //$("#tbl_usersearch").dataTable({
            //    searching: false, info: false, lengthChange: false, "dom": 'frti<"add_message">p',
            //});
            //var add_html =
            //    '<div id="div_message" class="float_right ">' +
            //    '<img id="img_success" class="" src="/Content/Icons/success.png" style="height:18px;" />' +
            //    '<img id="img_warning" class="" src="/Content/Icons/warning.png" style="height:18px;" />' +
            //    '<span id="lbl_message">Message</span>' +
            //    '</div>';
            //$("div.add_message").html(add_html);


            $("#div_roleusers").find("#tbl_userroles").dataTable({
                searching: false, info: false, lengthChange: false
            });

        });

        // --------------------------------------------------------------------------------
        function SearchUsers() {
            console.log("SearchUsers:");
            $('#hdn_status').val("SearchUsers");
            $('form#myform').submit();
            return false;
        }

        // --------------------------------------------------------------------------------
        function AddUser(Id) {
            console.log("AddUser:" + Id);
            ShowMessage($('#div_add_message'), "Processing...", null);
            $('#hdn_key').val(Id);
            $('#hdn_status').val("AddUser");
            $('form#myform').submit();
            return false;
        }

        // --------------------------------------------------------------------------------
        function RemoveUser(Id) {
            console.log("RemoveUser:" + Id);
            ShowMessage($('#div_remove_message'), "Processing...", null);
            $('#hdn_key').val(Id);
            $('#hdn_status').val("RemoveUser");
            $('form#myform').submit();
            return false;
        }

        // --------------------------------------------------------------------------------
        function OnBegin() {
            console.log("OnBegin");
            DisableInputs(true);
        }

        // --------------------------------------------------------------------------------
        function OnSuccess(data, status, xhr) {
            console.log("OnSuccess");
            DisableInputs(false);

            var srchMessage = xhr.getResponseHeader("srchMessage")
            if (srchMessage != null) {
                var srchJson = JSON.parse(srchMessage);

                $("#div_usersearch").html(data);
                $("#div_usersearch").find("#tbl_usersearch").dataTable({
                    searching: false, info: false, lengthChange: false
                });

                return;
            }

            if (xhr.responseJSON != null) {
                if (xhr.responseJSON.param1 == "AddUserRole") {
                    ShowMessage($('#div_add_message'), "User was added to role.", false);
                    MoveTableRow('tbl_usersearch', 'tbl_userroles', xhr.responseJSON.param2, "Add", "Remove");
                    return;
                }

                if (xhr.responseJSON.param1 == "RemoveUserRole") {
                    ShowMessage($('#div_remove_message'), "User was removed from role.", false);
                    MoveTableRow('tbl_userroles', 'tbl_usersearch', xhr.responseJSON.param2, "Remove", "Add");
                    return;
                }
            }

        }

        // --------------------------------------------------------------------------------
        function MoveTableRow(from_tablename, to_tablename, row_id, replace_from_string, replace_to_string) {
            var table1 = $('#' + from_tablename + '').DataTable();
            var table2 = $('#' + to_tablename + '').DataTable();

            var table1_row = table1.row("#" + row_id + "");
            var cells1 = table1_row.data();
            table1_row.remove().draw(false);

            var re = new RegExp(replace_from_string, 'g');
            var new_button_href = cells1[4].replace(re, replace_to_string);


            table2.row.add([cells1[0], cells1[1], cells1[2], cells1[3], new_button_href]).draw(false).node().id = row_id;


        }

        // --------------------------------------------------------------------------------
        function OnFailure(xhr, status) {
            console.log("OnFailure");
            DisableInputs(false);
            $("#btn_submit").text("Create Account");
            if (xhr.responseJSON.param1 == "RoleName") {
                $("#RoleName").removeClass("lgreen");
                $("#RoleName").addClass("lred");
                $("#RoleNameError").removeClass("hidden");
                $("#RoleNameError").text(xhr.responseJSON.param3);
            }
        }


    </script>
}


LoginApp1/Views/AppRoles/CreateAppRole.cshtml
@model LoginApp1.Models.Account.AppRole

@{
    ViewBag.Title = "CreateAppRole";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@using (Ajax.BeginForm("CreateAppRole", "AppRoles", null,
    new AjaxOptions
    {
        HttpMethod = "Post",
        OnBegin = "OnBegin",
        OnFailure = "OnFailure(xhr, status)",
        OnSuccess = "OnSuccess"
    },
    new { id = "myform" }))
{

    @Html.AntiForgeryToken()
        
    <div class="logo mb-3">
        <div class="col-md-12 text-center">
            <h2>Edit the application role:</h2>
        </div>
    </div>

    <div class="col-xs-1"></div>
    <div class="col-xs-10">
        <div>
            <div id="div_message" class="float_right lcl_hidden">
                <img id="img_success" class="lcl_hidden" src="~/Content/Icons/success.png" style="height:18px;" />
                <img id="img_warning" class="lcl_hidden" src="~/Content/Icons/warning.png" style="height:18px;" />
                <span id="lbl_message">Message</span>
            </div>
        </div>

        <div>
            @Html.ActionLink("Back to roles list", "IndexAppRoles")
        </div>
        <div class="form-horizontal">
            <hr class="margin_bottom_small" />
            <h4>Edit the application role details:</h4>

            <div class="row margin_bottom_small">
                <div class="col-xs-3 margin_bottom_small">
                    @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label" })
                    @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @id = "RoleName",  @class = "form-control small_inp_box" } })
                    @Html.ValidationMessageFor(model => model.Name, "", new { @id = "RoleNameError",  @class = "text-danger static_error" })
                </div>
                <div class="col-xs-4  margin_left_2em">
                    @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label" })
                    @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @id = "RoleDescription", @class = "form-control small_inp_box" } })
                    @Html.ValidationMessageFor(model => model.Description, "", new { @id = "RoleDescriptionError", @class = "text-danger static_error" })
                </div>
                <div class="col-xs-1  margin_left_2em">
                    <label class="control-label">&nbsp;</label>
                    <label class="control-label">&nbsp;</label>
                    <input type="submit" id="btn_submit" value="Save Role" class="btn btn-default btn-primary" />
                </div>
            </div>

            <hr class="margin_top_none margin_bottom_none" />
        </div>
    </div>
    <div class="col-xs-1"></div>
    <br style="clear:both;" />

    <div class="form-horizontal">
        <div class="col-xs-1"></div>
        <div class="col-xs-10">
            <h4>Add or remove users to this role:</h4>

            <table class="table-bordered table-striped">
                <thead>
                    <tr>
                        <td>User Id</td>
                        <td>User Name</td>
                        <td>User Desc</td>
                        <td>Action</td>
                    </tr>
                </thead>

                <tbody>
                    <tr>
                        <td>User Id</td>
                        <td>User Name</td>
                        <td>User Desc</td>
                        <td>Action</td>
                    </tr>
                </tbody>

            </table>
            <br style="clear:both;" />
            <div class="col-xs-2 form-group">
                <input type="submit" value="Save Changes" class="btn btn-default btn-primary" />
            </div>

            <br style="clear:both;" />
            <hr />
        </div>
        <div class="col-xs-1"></div>
        <br style="clear:both;" />
    </div>

}


@section scripts{
    <script>
        $(document).ready(function () {
            console.log("ready to rock and roll....");
            $(".small_inp_box:first").focus();
            $(".small_inp_box").addClass("lgreen");
        });

        function OnBegin() {
            console.log("OnBegin");
            DisableInputs(true);
        }

        function OnSuccess() {
            console.log("OnSuccess");
            DisableInputs(false);
            ShowMessage("Role was created.", false);
            $("#RoleName").removeClass("lred");
            $("#RoleName").addClass("lgreen");
            $("#RoleNameError").addClass("hidden");
            $("#RoleNameError").text('');
        }

        function OnFailure(xhr, status) {
            console.log("OnFailure");
            DisableInputs(false);
            $("#btn_submit").text("Create Account");
            ShowMessage("Update failed.", true);
            if (xhr.responseJSON.param1 == "RoleName") {
                $("#RoleName").removeClass("lgreen");
                $("#RoleName").addClass("lred");
                $("#RoleNameError").removeClass("hidden");
                $("#RoleNameError").text(xhr.responseJSON.param3);
            }
        }

        function ShowMessage(message, error) {
            if (error) {
                $("#img_success").hide();
                $("#img_warning").show();
            }
            else {
                $("#img_success").show();
                $("#img_warning").hide();
            }
            $("#lbl_message").text(message);
            $("#div_message").show();
            setTimeout(function () {
                $("#div_message").hide();
            }, 5000);
        }

        function DisableInputs(flag) {
            if (flag) {
                $(".small_inp_box").prop("disabled", true);
                $("input:password").prop("disabled", true);
                $("#btn_submit").prop("disabled", true);
                $("#btn_submit").text("Processing", true);
            }
            else {
                $(".small_inp_box").prop("disabled", false);
                $("input:password").prop("disabled", false);
                $("#btn_submit").prop("disabled", false);
                $("#btn_submit").text("Save Role");
            }
        }

        $(".small_inp_box").focusout(function () {
            console.log("checking for invalids");
            var fv = $('#myform').validate();
            if (!$(this).valid()) {
                $(this).removeClass("lgreen");
                $(this).addClass("lred");
            }
            else {
                $(this).addClass("lgreen");
                $(this).removeClass("lred");
                console.log("valid!");
            }
        });

    </script>
}

LoginApp1/Views/AppRoles/EditUserRolesPartial.cshtml
@model LoginApp1.Models.Account.AppRoleView


<div class="form-horizontal">
    <div class="col-xs-1"></div>
    <div class="col-xs-10">
        <table id="tbl_userroles" class="table-bordered table-striped">
            <thead>
                <tr>
                    <td>User Id</td>
                    <td>User Name</td>
                    <td>User Desc</td>
                    <td>Action</td>
                </tr>
            </thead>

            <tbody>
                <tr>
                    <td>User Id</td>
                    <td>User Name</td>
                    <td>User Desc</td>
                    <td>Action</td>
                </tr>
            </tbody>

        </table>
        <div class="col-xs-2 form-group">
            <input type="submit" value="Save Changes" class="btn btn-default btn-primary" />
        </div>

        <br style="clear:both;" />
        <hr />
    </div>
    <div class="col-xs-1"></div>
    <br style="clear:both;" />
</div>

LoginApp1/Views/AppRoles/RoleUsersTable.cshtml
@model LoginApp1.Models.Account.AppRoleView

<table id="tbl_userroles" class="table-bordered table-striped">
    <thead>
        <tr>
            <td>User Id</td>
            <td>User Name</td>
            <td>First Name</td>
            <td>Last Name</td>
            <td>Action</td>
        </tr>
    </thead>

    <tbody>
        @if (Model.appUsers != null)
        {
            foreach (var item in Model.appUsers)
            {
                <tr id="@item.Id">
                    <td>
                        @Html.DisplayFor(modelItem => item.UserId)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.UserName)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.FirstName)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.LastName)
                    </td>
                    <td>
                        <button id="btn_remove"
                                type="button"
                                class="btn btn-link btn-nopad"
                                value="@item.Id"
                                onclick="javascript:return RemoveUser(value)">
                            Remove
                        </button>
                    </td>
                </tr>
            }
        }
    </tbody>

</table>